-- Metric target templates: reusable baseline targets that can be applied to any month.
-- Applying a template to a month creates metric_targets for that month's monthly period
-- and for each ISO week whose Monday falls within that month.

CREATE TABLE metric_target_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_name text NOT NULL DEFAULT 'Default',
  metric_key text NOT NULL REFERENCES metric_definitions(metric_key),
  period_type text NOT NULL CHECK (period_type IN ('WEEK', 'MONTH')),
  target_value numeric NOT NULL,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT uq_template_metric UNIQUE (template_name, metric_key, period_type)
);

CREATE INDEX idx_metric_target_templates_name ON metric_target_templates (template_name);

ALTER TABLE metric_target_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY authenticated_access_metric_target_templates
  ON metric_target_templates FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY service_role_bypass_metric_target_templates
  ON metric_target_templates FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

COMMENT ON TABLE metric_target_templates IS 'Reusable target templates. Apply a template to a month to bulk-create metric_targets for that month and its weeks.';
