-- Target Management: store weekly or monthly targets for business metrics.
-- period_start: for MONTH = first day of month (YYYY-MM-01); for WEEK = Monday of that week.

CREATE TABLE metric_targets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_key text NOT NULL,
  period_type text NOT NULL CHECK (period_type IN ('WEEK', 'MONTH')),
  period_start date NOT NULL,
  target_value numeric NOT NULL,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT uq_metric_targets_key_period UNIQUE (metric_key, period_type, period_start)
);

CREATE INDEX idx_metric_targets_period ON metric_targets (period_type, period_start);
CREATE INDEX idx_metric_targets_metric_key ON metric_targets (metric_key);

COMMENT ON TABLE metric_targets IS 'Business performance targets by metric and period (week or month). Used by executive reporting for actual vs target comparison.';
